import { UserProfile } from '@/types/user';
import { Match } from '@/types/match';
import { ChatMessage } from '@/types/chat';

export const MOCK_CURRENT_USER: UserProfile = {
  userId: 'demo-user-1',
  firstName: 'Aria',
  dateOfBirth: '1998-10-28',
  birthTime: '14:32',
  birthCity: 'Paris',
  birthCountry: 'France',
  gender: 'female',
  interestedIn: 'everyone',
  age: 26,
  bio: 'Scorpio Sun, Pisces Moon, Sagittarius Rising. Architect by day, stargazer & vinyl record hunter by night. Looking for someone with electric curiosity and emotional depth.',
  profilePhotos: [
    'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
  ],
  location: {
    city: 'Paris',
    country: 'France',
    lat: 48.8566,
    lng: 2.3522,
    distanceKm: 0,
  },
  relationshipIntent: 'long-term',
  interests: ['Astrology', 'Modern Art', 'Stargazing', 'Vinyl Records', 'Espresso', 'Indie Cinema'],
  sunSign: 'Scorpio',
  moonSign: 'Pisces',
  risingSign: 'Sagittarius',
  venusSign: 'Scorpio',
  marsSign: 'Capricorn',
  subscriptionTier: 'vip',
  astrologyCompleted: true,
  createdAt: '2024-01-15T10:00:00Z',
  updatedAt: '2024-01-15T10:00:00Z',
};

export const MOCK_DISCOVER_PROFILES: UserProfile[] = [
  {
    userId: 'user-elena',
    firstName: 'Elena',
    dateOfBirth: '1999-03-12',
    birthTime: '09:15',
    birthCity: 'Florence',
    birthCountry: 'Italy',
    gender: 'female',
    interestedIn: 'everyone',
    age: 25,
    bio: 'Pisces Sun, Cancer Moon, Taurus Rising. Curator at an independent contemporary gallery. I believe in magnetic synchronicities, late night museum walks, and deep elemental conversations.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1503185912284-5271ff81b9a8?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 3 },
    relationshipIntent: 'long-term',
    interests: ['Art Curation', 'Poetry', 'Astrology', 'Wine Tasting', 'Analog Photography'],
    sunSign: 'Pisces',
    moonSign: 'Cancer',
    risingSign: 'Taurus',
    venusSign: 'Pisces',
    marsSign: 'Taurus',
    astrologyCompleted: true,
    createdAt: '2024-02-01T12:00:00Z',
    updatedAt: '2024-02-01T12:00:00Z',
  },
  {
    userId: 'user-julian',
    firstName: 'Julian',
    dateOfBirth: '1997-07-29',
    birthTime: '18:45',
    birthCity: 'Barcelona',
    birthCountry: 'Spain',
    gender: 'male',
    interestedIn: 'everyone',
    age: 27,
    bio: 'Leo Sun, Aries Moon, Libra Rising. Music producer and sound designer. Warm fire energy with a deep love for acoustic instruments and spontaneous road trips into the mountains.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 5 },
    relationshipIntent: 'long-term',
    interests: ['Music Production', 'Synthesizers', 'Bouldering', 'Coffee Roasting', 'Cinema'],
    sunSign: 'Leo',
    moonSign: 'Aries',
    risingSign: 'Libra',
    venusSign: 'Leo',
    marsSign: 'Virgo',
    astrologyCompleted: true,
    createdAt: '2024-02-05T15:30:00Z',
    updatedAt: '2024-02-05T15:30:00Z',
  },
  {
    userId: 'user-maya',
    firstName: 'Maya',
    dateOfBirth: '1998-05-14',
    birthTime: '06:20',
    birthCity: 'Athens',
    birthCountry: 'Greece',
    gender: 'female',
    interestedIn: 'everyone',
    age: 26,
    bio: 'Taurus Sun, Capricorn Moon, Virgo Rising. Landscape designer & botanical illustrator. Rooted, calm, and obsessed with creating secret garden sanctuaries.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 7 },
    relationshipIntent: 'long-term',
    interests: ['Botany', 'Ceramics', 'Slow Cooking', 'Hiking', 'Architecture'],
    sunSign: 'Taurus',
    moonSign: 'Capricorn',
    risingSign: 'Virgo',
    venusSign: 'Cancer',
    marsSign: 'Taurus',
    astrologyCompleted: true,
    createdAt: '2024-02-10T08:00:00Z',
    updatedAt: '2024-02-10T08:00:00Z',
  },
  {
    userId: 'user-lucas',
    firstName: 'Lucas',
    dateOfBirth: '1996-11-18',
    birthTime: '23:10',
    birthCity: 'Lyon',
    birthCountry: 'France',
    gender: 'male',
    interestedIn: 'everyone',
    age: 28,
    bio: 'Scorpio Sun, Taurus Moon, Scorpio Rising. Astrophysics researcher. Fascinated by gravitational waves and the unspoken gravity between two minds.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 2 },
    relationshipIntent: 'long-term',
    interests: ['Astrophysics', 'Chess', 'Dark Chocolate', 'Jazz', 'Philosophy'],
    sunSign: 'Scorpio',
    moonSign: 'Taurus',
    risingSign: 'Scorpio',
    venusSign: 'Sagittarius',
    marsSign: 'Aquarius',
    astrologyCompleted: true,
    createdAt: '2024-02-12T19:00:00Z',
    updatedAt: '2024-02-12T19:00:00Z',
  },
  {
    userId: 'user-sophie',
    firstName: 'Sophie',
    dateOfBirth: '2000-01-28',
    birthTime: '11:05',
    birthCity: 'Berlin',
    birthCountry: 'Germany',
    gender: 'female',
    interestedIn: 'everyone',
    age: 24,
    bio: 'Aquarius Sun, Gemini Moon, Aries Rising. AI UX researcher. Unapologetically eccentric, high-energy intellectual debates, neon aesthetics, and synth-pop.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1488426862026-3ee34a7d66fc?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 8 },
    relationshipIntent: 'figuring-out',
    interests: ['Cybernetics', 'Electronic Music', 'Sci-Fi', 'Night Drives', 'Baking'],
    sunSign: 'Aquarius',
    moonSign: 'Gemini',
    risingSign: 'Aries',
    venusSign: 'Aquarius',
    marsSign: 'Pisces',
    astrologyCompleted: true,
    createdAt: '2024-02-15T14:10:00Z',
    updatedAt: '2024-02-15T14:10:00Z',
  },
  {
    userId: 'user-mateo',
    firstName: 'Mateo',
    dateOfBirth: '1995-09-08',
    birthTime: '07:45',
    birthCity: 'Madrid',
    birthCountry: 'Spain',
    gender: 'male',
    interestedIn: 'female',
    age: 29,
    bio: 'Virgo Sun, Taurus Moon, Capricorn Rising. Earth architect specializing in sustainable timber structures. Passionate about sourdough baking, mid-century furniture, and quiet stargazing.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1480455624315-06be489e18f0?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 6 },
    relationshipIntent: 'marriage',
    interests: ['Architecture', 'Woodworking', 'Coffee', 'Nature', 'Vinyl Records'],
    sunSign: 'Virgo',
    moonSign: 'Taurus',
    risingSign: 'Capricorn',
    venusSign: 'Virgo',
    marsSign: 'Scorpio',
    astrologyCompleted: true,
    createdAt: '2024-02-16T10:00:00Z',
    updatedAt: '2024-02-16T10:00:00Z',
  },
  {
    userId: 'user-chloe',
    firstName: 'Chloé',
    dateOfBirth: '1997-10-04',
    birthTime: '15:20',
    birthCity: 'Nice',
    birthCountry: 'France',
    gender: 'female',
    interestedIn: 'everyone',
    age: 27,
    bio: 'Libra Sun, Sagittarius Moon, Gemini Rising. Perfumer & scent designer. In search of balance, beauty, and someone who appreciates the nuance of notes and celestial alignments.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 4 },
    relationshipIntent: 'long-term',
    interests: ['Perfumery', 'French Cinema', 'Astrology', 'Modern Dance', 'Matcha'],
    sunSign: 'Libra',
    moonSign: 'Sagittarius',
    risingSign: 'Gemini',
    venusSign: 'Scorpio',
    marsSign: 'Sagittarius',
    astrologyCompleted: true,
    createdAt: '2024-02-18T11:00:00Z',
    updatedAt: '2024-02-18T11:00:00Z',
  },
  {
    userId: 'user-gabriel',
    firstName: 'Gabriel',
    dateOfBirth: '1998-12-05',
    birthTime: '22:15',
    birthCity: 'Rio de Janeiro',
    birthCountry: 'Brazil',
    gender: 'male',
    interestedIn: 'everyone',
    age: 26,
    bio: 'Sagittarius Sun, Leo Moon, Aries Rising. Triple fire powerhouse! Documentary filmmaker telling stories of oceanic conservation. Adventure is non-negotiable.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 9 },
    relationshipIntent: 'long-term',
    interests: ['Filmmaking', 'Surfing', 'Astronomy', 'Samba', 'Travel'],
    sunSign: 'Sagittarius',
    moonSign: 'Leo',
    risingSign: 'Aries',
    venusSign: 'Capricorn',
    marsSign: 'Sagittarius',
    astrologyCompleted: true,
    createdAt: '2024-02-20T16:00:00Z',
    updatedAt: '2024-02-20T16:00:00Z',
  },
  {
    userId: 'user-zara',
    firstName: 'Zara',
    dateOfBirth: '1996-04-08',
    birthTime: '04:30',
    birthCity: 'London',
    birthCountry: 'United Kingdom',
    gender: 'female',
    interestedIn: 'everyone',
    age: 28,
    bio: 'Aries Sun, Scorpio Moon, Leo Rising. Fashion creative director. Direct, passionate, and fiercely loyal. Let us build an empire or spend Sundays getting lost in bookstores.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1503185912284-5271ff81b9a8?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 12 },
    relationshipIntent: 'marriage',
    interests: ['Haute Couture', 'Fine Art', 'Boxing', 'Philosophy', 'Astrology'],
    sunSign: 'Aries',
    moonSign: 'Scorpio',
    risingSign: 'Leo',
    venusSign: 'Taurus',
    marsSign: 'Aries',
    astrologyCompleted: true,
    createdAt: '2024-02-22T13:45:00Z',
    updatedAt: '2024-02-22T13:45:00Z',
  },
  {
    userId: 'user-kai',
    firstName: 'Kai',
    dateOfBirth: '1999-06-15',
    birthTime: '13:00',
    birthCity: 'Tokyo',
    birthCountry: 'Japan',
    gender: 'non-binary',
    interestedIn: 'everyone',
    age: 25,
    bio: 'Gemini Sun, Aquarius Moon, Libra Rising. Triple Air intellectual. Generative artist and game writer. Endless curiosity, late-night tea ceremonies, and ambient techno.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 4 },
    relationshipIntent: 'figuring-out',
    interests: ['Generative Art', 'Tea Culture', 'Game Design', 'Poetry', 'Astronomy'],
    sunSign: 'Gemini',
    moonSign: 'Aquarius',
    risingSign: 'Libra',
    venusSign: 'Gemini',
    marsSign: 'Cancer',
    astrologyCompleted: true,
    createdAt: '2024-02-24T09:00:00Z',
    updatedAt: '2024-02-24T09:00:00Z',
  },
  {
    userId: 'user-camille',
    firstName: 'Camille',
    dateOfBirth: '1997-06-25',
    birthTime: '02:40',
    birthCity: 'Bordeaux',
    birthCountry: 'France',
    gender: 'female',
    interestedIn: 'everyone',
    age: 27,
    bio: 'Cancer Sun, Pisces Moon, Cancer Rising. Cellist and composer. Intuitive, warm, and deeply protective of those I love. I speak the language of music and quiet understanding.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 3 },
    relationshipIntent: 'long-term',
    interests: ['Classical Music', 'Cello', 'Astrology', 'Vintage Books', 'Baking'],
    sunSign: 'Cancer',
    moonSign: 'Pisces',
    risingSign: 'Cancer',
    venusSign: 'Leo',
    marsSign: 'Virgo',
    astrologyCompleted: true,
    createdAt: '2024-02-25T18:00:00Z',
    updatedAt: '2024-02-25T18:00:00Z',
  },
  {
    userId: 'user-nathan',
    firstName: 'Nathan',
    dateOfBirth: '1995-01-14',
    birthTime: '08:30',
    birthCity: 'Zurich',
    birthCountry: 'Switzerland',
    gender: 'male',
    interestedIn: 'everyone',
    age: 29,
    bio: 'Capricorn Sun, Virgo Moon, Scorpio Rising. Quantitative analyst with a secret passion for mountaineering and classical piano. Ambition balanced with steady loyalty.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1480455624315-06be489e18f0?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 6 },
    relationshipIntent: 'marriage',
    interests: ['Mountaineering', 'Piano', 'Finance', 'Espresso', 'Chess'],
    sunSign: 'Capricorn',
    moonSign: 'Virgo',
    risingSign: 'Scorpio',
    venusSign: 'Aquarius',
    marsSign: 'Aries',
    astrologyCompleted: true,
    createdAt: '2024-02-26T12:00:00Z',
    updatedAt: '2024-02-26T12:00:00Z',
  },
  {
    userId: 'user-leila',
    firstName: 'Leila',
    dateOfBirth: '1999-08-19',
    birthTime: '17:15',
    birthCity: 'Cairo',
    birthCountry: 'Egypt',
    gender: 'female',
    interestedIn: 'everyone',
    age: 25,
    bio: 'Leo Sun, Sagittarius Moon, Libra Rising. Jewelry designer & gemologist. Golden hour lover, collector of ancient myths, and lover of warm desert nights.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1503185912284-5271ff81b9a8?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 8 },
    relationshipIntent: 'long-term',
    interests: ['Gemology', 'Mythology', 'Design', 'Middle Eastern Cuisine', 'Yoga'],
    sunSign: 'Leo',
    moonSign: 'Sagittarius',
    risingSign: 'Libra',
    venusSign: 'Virgo',
    marsSign: 'Scorpio',
    astrologyCompleted: true,
    createdAt: '2024-02-27T15:20:00Z',
    updatedAt: '2024-02-27T15:20:00Z',
  },
  {
    userId: 'user-samuel',
    firstName: 'Samuel',
    dateOfBirth: '1996-03-30',
    birthTime: '05:50',
    birthCity: 'Toronto',
    birthCountry: 'Canada',
    gender: 'male',
    interestedIn: 'everyone',
    age: 28,
    bio: 'Aries Sun, Leo Moon, Sagittarius Rising. Triple Fire trail runner & adventure photographer. High enthusiasm, authentic presence, and an obsession with sunrise summits.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 11 },
    relationshipIntent: 'long-term',
    interests: ['Trail Running', 'Photography', 'Camping', 'Espresso', 'Astrophotography'],
    sunSign: 'Aries',
    moonSign: 'Leo',
    risingSign: 'Sagittarius',
    venusSign: 'Pisces',
    marsSign: 'Sagittarius',
    astrologyCompleted: true,
    createdAt: '2024-02-28T09:10:00Z',
    updatedAt: '2024-02-28T09:10:00Z',
  },
  {
    userId: 'user-isabella',
    firstName: 'Isabella',
    dateOfBirth: '1998-02-14',
    birthTime: '20:10',
    birthCity: 'Rome',
    birthCountry: 'Italy',
    gender: 'female',
    interestedIn: 'everyone',
    age: 26,
    bio: 'Aquarius Sun, Libra Moon, Gemini Rising. Romantic Air archetype. Renaissance art historian and rare book restorer. Looking for someone with boundless intellect and kindness.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 4 },
    relationshipIntent: 'long-term',
    interests: ['Art History', 'Bookbinding', 'Italian Cinema', 'Poetry', 'Astrology'],
    sunSign: 'Aquarius',
    moonSign: 'Libra',
    risingSign: 'Gemini',
    venusSign: 'Capricorn',
    marsSign: 'Pisces',
    astrologyCompleted: true,
    createdAt: '2024-03-01T11:00:00Z',
    updatedAt: '2024-03-01T11:00:00Z',
  },
  {
    userId: 'user-alexandre',
    firstName: 'Alexandre',
    dateOfBirth: '1997-04-24',
    birthTime: '12:35',
    birthCity: 'Geneva',
    birthCountry: 'Switzerland',
    gender: 'male',
    interestedIn: 'everyone',
    age: 27,
    bio: 'Taurus Sun, Cancer Moon, Virgo Rising. Watchmaker and kinetic artist. Deeply sensual, appreciates fine craftsmanship, and loves cooking elaborate four-course dinners.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1480455624315-06be489e18f0?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 5 },
    relationshipIntent: 'marriage',
    interests: ['Horology', 'Gastronomy', 'Jazz', 'Antiques', 'Wine'],
    sunSign: 'Taurus',
    moonSign: 'Cancer',
    risingSign: 'Virgo',
    venusSign: 'Aries',
    marsSign: 'Taurus',
    astrologyCompleted: true,
    createdAt: '2024-03-02T14:00:00Z',
    updatedAt: '2024-03-02T14:00:00Z',
  },
  {
    userId: 'user-mia',
    firstName: 'Mia',
    dateOfBirth: '2000-11-02',
    birthTime: '01:15',
    birthCity: 'Stockholm',
    birthCountry: 'Sweden',
    gender: 'female',
    interestedIn: 'everyone',
    age: 24,
    bio: 'Scorpio Sun, Capricorn Moon, Pisces Rising. Scandinavian lighting designer. Magnetically quiet, dark humor, winter ocean dips, and passionate late night conversations.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1503185912284-5271ff81b9a8?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 7 },
    relationshipIntent: 'long-term',
    interests: ['Lighting Design', 'Sauna', 'Architecture', 'Indie Rock', 'Astrology'],
    sunSign: 'Scorpio',
    moonSign: 'Capricorn',
    risingSign: 'Pisces',
    venusSign: 'Sagittarius',
    marsSign: 'Libra',
    astrologyCompleted: true,
    createdAt: '2024-03-03T16:30:00Z',
    updatedAt: '2024-03-03T16:30:00Z',
  },
  {
    userId: 'user-theo',
    firstName: 'Théo',
    dateOfBirth: '1995-05-30',
    birthTime: '10:00',
    birthCity: 'Marseille',
    birthCountry: 'France',
    gender: 'male',
    interestedIn: 'everyone',
    age: 29,
    bio: 'Gemini Sun, Aries Moon, Leo Rising. Mediterranean sailor & marine biologist. Fast wit, constant laughter, and an insatiable desire to explore uncharted coastlines.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 8 },
    relationshipIntent: 'long-term',
    interests: ['Sailing', 'Marine Biology', 'Freediving', 'Acoustic Guitar', 'Travel'],
    sunSign: 'Gemini',
    moonSign: 'Aries',
    risingSign: 'Leo',
    venusSign: 'Cancer',
    marsSign: 'Virgo',
    astrologyCompleted: true,
    createdAt: '2024-03-04T12:00:00Z',
    updatedAt: '2024-03-04T12:00:00Z',
  },
  {
    userId: 'user-ananya',
    firstName: 'Ananya',
    dateOfBirth: '1998-09-21',
    birthTime: '19:40',
    birthCity: 'Mumbai',
    birthCountry: 'India',
    gender: 'female',
    interestedIn: 'everyone',
    age: 26,
    bio: 'Virgo Sun, Taurus Moon, Scorpio Rising. Cognitive scientist & meditation instructor. Grounded intellect meeting spiritual mysticism. Seeking authentic depth.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 5 },
    relationshipIntent: 'marriage',
    interests: ['Cognitive Science', 'Meditation', 'Classical Dance', 'Ayurveda', 'Literature'],
    sunSign: 'Virgo',
    moonSign: 'Taurus',
    risingSign: 'Scorpio',
    venusSign: 'Leo',
    marsSign: 'Virgo',
    astrologyCompleted: true,
    createdAt: '2024-03-05T08:00:00Z',
    updatedAt: '2024-03-05T08:00:00Z',
  },
  {
    userId: 'user-liam',
    firstName: 'Liam',
    dateOfBirth: '1996-07-08',
    birthTime: '21:50',
    birthCity: 'Dublin',
    birthCountry: 'Ireland',
    gender: 'male',
    interestedIn: 'everyone',
    age: 28,
    bio: 'Cancer Sun, Pisces Moon, Scorpio Rising. Triple Water emotional depth. Author & folklorist. Warm firesides, stormy rainy days, and heartfelt poetic conversations.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1480455624315-06be489e18f0?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 6 },
    relationshipIntent: 'long-term',
    interests: ['Creative Writing', 'Folklore', 'Whiskey Tasting', 'Poetry', 'Guitar'],
    sunSign: 'Cancer',
    moonSign: 'Pisces',
    risingSign: 'Scorpio',
    venusSign: 'Gemini',
    marsSign: 'Leo',
    astrologyCompleted: true,
    createdAt: '2024-03-06T10:30:00Z',
    updatedAt: '2024-03-06T10:30:00Z',
  },
  {
    userId: 'user-clara',
    firstName: 'Clara',
    dateOfBirth: '1999-12-19',
    birthTime: '14:10',
    birthCity: 'Vienna',
    birthCountry: 'Austria',
    gender: 'female',
    interestedIn: 'everyone',
    age: 25,
    bio: 'Sagittarius Sun, Aries Moon, Leo Rising. Concert pianist & mountaineer. Vibrant energy, spontaneous weekend getaways, and deep discussions on the harmony of the universe.',
    profilePhotos: [
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1503185912284-5271ff81b9a8?auto=format&fit=crop&w=800&q=80',
    ],
    location: { city: 'Paris', country: 'France', distanceKm: 4 },
    relationshipIntent: 'long-term',
    interests: ['Piano', 'Alps', 'Opera', 'Philosophy', 'Astrology'],
    sunSign: 'Sagittarius',
    moonSign: 'Aries',
    risingSign: 'Leo',
    venusSign: 'Scorpio',
    marsSign: 'Aquarius',
    astrologyCompleted: true,
    createdAt: '2024-03-07T14:15:00Z',
    updatedAt: '2024-03-07T14:15:00Z',
  }
];

export const MOCK_INITIAL_MATCHES: Match[] = [
  {
    id: 'match-elena-aria',
    users: ['demo-user-1', 'user-elena'],
    profiles: {
      'demo-user-1': {
        firstName: 'Aria',
        photo: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=800&q=80',
        sunSign: 'Scorpio',
        age: 26,
      },
      'user-elena': {
        firstName: 'Elena',
        photo: 'https://images.unsplash.com/photo-1503185912284-5271ff81b9a8?auto=format&fit=crop&w=800&q=80',
        sunSign: 'Pisces',
        age: 25,
      },
    },
    lastMessage: {
      text: 'The celestial trine between Scorpio and Pisces is undeniably powerful ✨',
      senderId: 'user-elena',
      sentAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      read: false,
    },
    unreadCount: {
      'demo-user-1': 1,
      'user-elena': 0,
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'match-lucas-aria',
    users: ['demo-user-1', 'user-lucas'],
    profiles: {
      'demo-user-1': {
        firstName: 'Aria',
        photo: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=800&q=80',
        sunSign: 'Scorpio',
        age: 26,
      },
      'user-lucas': {
        firstName: 'Lucas',
        photo: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=800&q=80',
        sunSign: 'Scorpio',
        age: 28,
      },
    },
    lastMessage: {
      text: 'Are you going to the Observatory exhibition this Thursday?',
      senderId: 'user-lucas',
      sentAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
      read: true,
    },
    unreadCount: {
      'demo-user-1': 0,
      'user-lucas': 0,
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  }
];

export const MOCK_INITIAL_MESSAGES: Record<string, ChatMessage[]> = {
  'match-elena-aria': [
    {
      id: 'msg-1',
      matchId: 'match-elena-aria',
      senderId: 'demo-user-1',
      receiverId: 'user-elena',
      text: 'Hi Elena! I saw you curate contemporary art and your Pisces placement resonated immediately 🌙',
      createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      read: true,
    },
    {
      id: 'msg-2',
      matchId: 'match-elena-aria',
      senderId: 'user-elena',
      receiverId: 'demo-user-1',
      text: 'Hello Aria! That is so sweet. I love your architectural eye and your Scorpio intensity.',
      createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      read: true,
    },
    {
      id: 'msg-3',
      matchId: 'match-elena-aria',
      senderId: 'user-elena',
      receiverId: 'demo-user-1',
      text: 'The celestial trine between Scorpio and Pisces is undeniably powerful ✨',
      createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      read: false,
    },
  ],
  'match-lucas-aria': [
    {
      id: 'msg-l1',
      matchId: 'match-lucas-aria',
      senderId: 'demo-user-1',
      receiverId: 'user-lucas',
      text: 'Two Scorpios... this is either going to be legendary or dangerously magnetic ⚡',
      createdAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
      read: true,
    },
    {
      id: 'msg-l2',
      matchId: 'match-lucas-aria',
      senderId: 'user-lucas',
      receiverId: 'demo-user-1',
      text: 'Haha, definitely legendary. Gravitational waves never lie.',
      createdAt: new Date(Date.now() - 1000 * 60 * 210).toISOString(),
      read: true,
    },
    {
      id: 'msg-l3',
      matchId: 'match-lucas-aria',
      senderId: 'user-lucas',
      receiverId: 'demo-user-1',
      text: 'Are you going to the Observatory exhibition this Thursday?',
      createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
      read: true,
    }
  ]
};

