import { ZodiacSign, ZodiacSignInfo, AstrologicalElement } from '@/types/astrology';

export const ZODIAC_SIGNS: Record<ZodiacSign, ZodiacSignInfo> = {
  Aries: {
    name: 'Aries',
    symbol: '♈',
    element: 'Fire',
    modality: 'Cardinal',
    rulingPlanet: 'Mars',
    dateRange: 'Mar 21 - Apr 19',
    traits: ['Passionate', 'Direct', 'Courageous', 'Spontaneous', 'Bold'],
    color: '#EF4444',
  },
  Taurus: {
    name: 'Taurus',
    symbol: '♉',
    element: 'Earth',
    modality: 'Fixed',
    rulingPlanet: 'Venus',
    dateRange: 'Apr 20 - May 20',
    traits: ['Sensual', 'Loyal', 'Grounded', 'Devoted', 'Patient'],
    color: '#10B981',
  },
  Gemini: {
    name: 'Gemini',
    symbol: '♊',
    element: 'Air',
    modality: 'Mutable',
    rulingPlanet: 'Mercury',
    dateRange: 'May 21 - Jun 20',
    traits: ['Witty', 'Curious', 'Charming', 'Versatile', 'Expressive'],
    color: '#F59E0B',
  },
  Cancer: {
    name: 'Cancer',
    symbol: '♋',
    element: 'Water',
    modality: 'Cardinal',
    rulingPlanet: 'Moon',
    dateRange: 'Jun 21 - Jul 22',
    traits: ['Intuitive', 'Nurturing', 'Deeply Romantic', 'Empathetic', 'Protective'],
    color: '#38BDF8',
  },
  Leo: {
    name: 'Leo',
    symbol: '♌',
    element: 'Fire',
    modality: 'Fixed',
    rulingPlanet: 'Sun',
    dateRange: 'Jul 23 - Aug 22',
    traits: ['Charismatic', 'Generous', 'Warmhearted', 'Radiant', 'Playful'],
    color: '#F59E0B',
  },
  Virgo: {
    name: 'Virgo',
    symbol: '♍',
    element: 'Earth',
    modality: 'Mutable',
    rulingPlanet: 'Mercury',
    dateRange: 'Aug 23 - Sep 22',
    traits: ['Thoughtful', 'Attentive', 'Devoted', 'Articulate', 'Refined'],
    color: '#059669',
  },
  Libra: {
    name: 'Libra',
    symbol: '♎',
    element: 'Air',
    modality: 'Cardinal',
    rulingPlanet: 'Venus',
    dateRange: 'Sep 23 - Oct 22',
    traits: ['Harmonious', 'Aesthetic', 'Charming', 'Romantic', 'Diplomatic'],
    color: '#EC4899',
  },
  Scorpio: {
    name: 'Scorpio',
    symbol: '♏',
    element: 'Water',
    modality: 'Fixed',
    rulingPlanet: 'Pluto / Mars',
    dateRange: 'Oct 23 - Nov 21',
    traits: ['Magnetic', 'Intense', 'Passionate', 'Deep', 'Fiercely Loyal'],
    color: '#8B5CF6',
  },
  Sagittarius: {
    name: 'Sagittarius',
    symbol: '♐',
    element: 'Fire',
    modality: 'Mutable',
    rulingPlanet: 'Jupiter',
    dateRange: 'Nov 22 - Dec 21',
    traits: ['Adventurous', 'Philosophical', 'Free-spirited', 'Honest', 'Optimistic'],
    color: '#6366F1',
  },
  Capricorn: {
    name: 'Capricorn',
    symbol: '♑',
    element: 'Earth',
    modality: 'Cardinal',
    rulingPlanet: 'Saturn',
    dateRange: 'Dec 22 - Jan 19',
    traits: ['Ambitious', 'Steadfast', 'Mature', 'Reliable', 'Strategic'],
    color: '#475569',
  },
  Aquarius: {
    name: 'Aquarius',
    symbol: '♒',
    element: 'Air',
    modality: 'Fixed',
    rulingPlanet: 'Uranus / Saturn',
    dateRange: 'Jan 20 - Feb 18',
    traits: ['Visionary', 'Original', 'Independent', 'Humanitarian', 'Intriguing'],
    color: '#06B6D4',
  },
  Pisces: {
    name: 'Pisces',
    symbol: '♓',
    element: 'Water',
    modality: 'Mutable',
    rulingPlanet: 'Neptune / Jupiter',
    dateRange: 'Feb 19 - Mar 20',
    traits: ['Dreamy', 'Mystical', 'Poetic', 'Soulful', 'Compassionate'],
    color: '#A855F7',
  },
};

export const ELEMENT_COLORS: Record<AstrologicalElement, { text: string; bg: string; border: string }> = {
  Fire: { text: 'text-amber-400', bg: 'bg-amber-500/10', border: 'border-amber-500/30' },
  Earth: { text: 'text-emerald-400', bg: 'bg-emerald-500/10', border: 'border-emerald-500/30' },
  Air: { text: 'text-cyan-400', bg: 'bg-cyan-500/10', border: 'border-cyan-500/30' },
  Water: { text: 'text-purple-400', bg: 'bg-purple-500/10', border: 'border-purple-500/30' },
};
